name: Trigger auto deployment for mygithubcontainerappup

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/mygithubcontainerappup-AutoDeployTrigger-a6320abd-3c4b-4073-a71b-3e73bc0f9f4a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca3300674236acr.azurecr.io
          username: ${{ secrets.MYGITHUBCONTAINERAPPUP_REGISTRY_USERNAME }}
          password: ${{ secrets.MYGITHUBCONTAINERAPPUP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca3300674236acr.azurecr.io/mygithubcontainerappup:${{ github.sha }}
          file: src/Dockerfile
          context: src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYGITHUBCONTAINERAPPUP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mygithubcontainerappup -g apwapr21 --server ca3300674236acr.azurecr.io --username  ${{ secrets.MYGITHUBCONTAINERAPPUP_REGISTRY_USERNAME }} --password ${{ secrets.MYGITHUBCONTAINERAPPUP_REGISTRY_PASSWORD }}
            az containerapp update -n mygithubcontainerappup -g apwapr21 --image ca3300674236acr.azurecr.io/mygithubcontainerappup:${{ github.sha }}
