name: Trigger auto deployment for mygithubcontainerappuppub

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/mygithubcontainerappuppub-AutoDeployTrigger-69658887-c069-4e1a-ae3b-3accf53265e6.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca2a243418d5acr.azurecr.io
          username: ${{ secrets.MYGITHUBCONTAINERAPPUPPUB_REGISTRY_USERNAME }}
          password: ${{ secrets.MYGITHUBCONTAINERAPPUPPUB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca2a243418d5acr.azurecr.io/mygithubcontainerappuppub:${{ github.sha }}
          file: src/Dockerfile
          context: src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYGITHUBCONTAINERAPPUPPUB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mygithubcontainerappuppub -g apwacauptest --server ca2a243418d5acr.azurecr.io --username  ${{ secrets.MYGITHUBCONTAINERAPPUPPUB_REGISTRY_USERNAME }} --password ${{ secrets.MYGITHUBCONTAINERAPPUPPUB_REGISTRY_PASSWORD }}
            az containerapp update -n mygithubcontainerappuppub -g apwacauptest --image ca2a243418d5acr.azurecr.io/mygithubcontainerappuppub:${{ github.sha }}
